version: '2'

services:
  prometheus_ethminer:
    container_name: prometheus_ethminer
    build: .
    environment:
      TEST_MODE: "${TEST_MODE}"
      MINER_ID: "${MINER_ID}"
      API_URL: "${API_URL}"
    ports:
      - "9201:9201"
